spring.application.name=FFXIV Crafting Aggregator
server.port=8090

jwt.secret = your-92-character-ultra-secure-secret-key-string-here!!!
jwt.expiration = 86400000

spring.datasource.url=jdbc:postgresql://localhost:5433/craft
spring.datasource.username=rayeed
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

