spring.application.name=FFXIV Crafting Aggregator
server.port=8090

spring.config.import=optional:file:./.env[.properties],optional:file:../.env[.properties]

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

xivapi.base-url = ${XIVAPI_BASE_URL:https://v2.xivapi.com}
universalis.base-url = ${UNIVERSALIS_BASE_URL:https://universalis.app}

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/${POSTGRES_DB:craft}?sslmode=${POSTGRES_SSL_MODE:disable}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

logging.level.org.springframework.security=info
logging.level.com.crafting.ffxivcraftingaggregator=DEBUG

spring.jackson.deserialization.fail-on-unknown-properties=false
